version: '3.1'

services:
  eventsdb:
    image: eventsdb
    build: ../eventsdb
    restart: always
    environment:
      - POSTGRES_PASSWORD=$EVENTSDB_PASSWORD
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./data/eventsdb:/var/lib/postgresql/data
