version: '3.1'

services:
  eventsdb:
    image: eventsdb
    build: ../eventsdb
    restart: always
    environment:
      - POSTGRES_PASSWORD=$EVENTSDB_PASSWORD
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./data/eventsdb:/var/lib/postgresql/data
  eventsapis:
    image: eventsapis
    build: ../eventsapis
    environment:
      - EVENTSDB_PASSWORD=$EVENTSDB_PASSWORD
      - RUST_LOG=server=trace
    volumes:
      - ../eventsapis/src:/app/src:ro
      - ../eventsapis/Cargo.lock:/app/Cargo.lock:ro
      - ../eventsapis/Cargo.toml:/app/Cargo.toml:ro
      - ../eventsapis-proto/Cargo.toml:/eventsapis-proto/Cargo.toml:ro
      - ../eventsapis-proto/Cargo.lock:/eventsapis-proto/Cargo.lock:ro
      - ../eventsapis-proto/src-rs:/eventsapis-proto/src-rs:ro
      - ../eventsapis-proto/proto:/eventsapis-proto/proto:ro
      - ../eventsapis-proto/build.rs:/eventsapis-proto/build.rs:ro
      - ./data/eventsapis/registry:/root/.cargo/registry:delegated
      - eventsapisbuildcache:/app/target
  eventsreducer:
    image: eventsreducer
    build: ../eventsreducer
    environment:
      - RUST_LOG=server=trace
    volumes:
      - ../eventsreducer/src:/app/src:ro
      - ../eventsreducer/proto:/app/proto:ro
      - ../eventsreducer/Cargo.lock:/app/Cargo.lock:ro
      - ../eventsreducer/Cargo.toml:/app/Cargo.toml:ro
      - ../postgresql-reducer/Cargo.toml:/postgresql-reducer/Cargo.toml:ro
      - ../postgresql-reducer/Cargo.lock:/postgresql-reducer/Cargo.lock:ro
      - ../postgresql-reducer/src:/postgresql-reducer/src:ro
      - ../eventsapis-proto/Cargo.toml:/eventsapis-proto/Cargo.toml:ro
      - ../eventsapis-proto/Cargo.lock:/eventsapis-proto/Cargo.lock:ro
      - ../eventsapis-proto/src-rs:/eventsapis-proto/src-rs:ro
      - ../eventsapis-proto/proto:/eventsapis-proto/proto:ro
      - ../eventsapis-proto/build.rs:/eventsapis-proto/build.rs:ro
      - ../reducerapis-proto/Cargo.toml:/reducerapis-proto/Cargo.toml:ro
      - ../reducerapis-proto/Cargo.lock:/reducerapis-proto/Cargo.lock:ro
      - ../reducerapis-proto/src:/reducerapis-proto/src:ro
      - ../reducerapis-proto/proto:/reducerapis-proto/proto:ro
      - ../reducerapis-proto/build.rs:/reducerapis-proto/build.rs:ro
      - ./data/eventsreducer/registry:/root/.cargo/registry:delegated
      - ./data/eventsreducer/postgresql-15:/data/postgresql-15:delegated
      - eventsreducerbuildcache:/app/target
  events-admin-dashboard:
    image: events-admin-dashboard
    build:
      context: ../events-admin-dashboard
      args:
        - GITHUB_TOKEN=$GITHUB_TOKEN
      secrets:
        - npmrc
    volumes:
      - ../events-admin-dashboard/src:/app/src:ro
  events-admin-proxy:
    image: nginx
    container_name: events-admin-proxy
    ports:
      - 3000:3000
    environment:
      - NGINX_PORT=3000
    volumes:
      - ./events-admin-proxy.conf:/etc/nginx/conf.d/default.conf

volumes:
  eventsapisbuildcache:
  eventsreducerbuildcache:

secrets:
  npmrc:
    file: .npmrc
